#!/bin/bash

start() {
    # TODO: move these to deb
    rm -f /etc/supervisor/conf.d/supervisord.conf
    cp ./supervisord.conf /etc/supervisor/conf.d/

    rm -f /etc/nginx/sites-enabled/*

    case "$2" in
        php)
            cp ./php.conf /etc/nginx/sites-enabled/
            root=$(readlink -f "$3")
            if [ ! -d "$root" ]; then
                echo "No such directory: $3"
                exit 1
            fi
            echo $root
            sed -i "s#root /root;#root $root;#" /etc/nginx/sites-enabled/php.conf
        ;;
        python)
            cp ./python.conf /etc/nginx/sites-enabled/
        ;;
    esac

    #sed -i "s#listen 80 default_server;#listen $port default_server;#" /etc/nginx/sites-enabled/php.conf

    APPLICATION_ENV=dev supervisord -c /etc/supervisor/conf.d/supervisord.conf

}

stop() {
    supervisorctl shutdown > /dev/null
    return 0
}

case "$1" in
    start)

            ;;
    stop)
        if stop; then
            echo "Stopped CS50 Server"
        fi
    ;;
esac
