#!/bin/bash

/bin/sed -i '/^env\[.\+\] *=.*/d' /etc/php5/fpm/pool.d/www.conf
/usr/bin/env | /bin/sed 's/\([^=]\+\)=\(.*\)/env[\1]=\"\2\"/' | /usr/bin/awk 'length <= 1024' >> /etc/php5/fpm/pool.d/www.conf
/usr/sbin/php5-fpm -F
