#!/bin/bash

# apache2
# TODO: conditionally enable php.ini directives for dev
if [ "$APPLICATION_ENV" == "dev" ]; then
    /usr/sbin/php5enmod xdebug && \
    /usr/sbin/apache2ctl -D FOREGROUND
else
    /usr/sbin/php5enmod xdebug && \
    /usr/sbin/apache2ctl -D FOREGROUND
fi
