#!/bin/bash

# restart application after every request in development mode
if [ "$APPLICATION_ENV" == "dev" ]; then
    mkdir -p tmp && touch tmp/always_restart.txt
fi

# configure Passenger, as per https://www.phusionpassenger.com/library/config/standalone/reference/
PASSENGER_LOG_FILE=/var/log/passenger.log \
PASSENGER_NGINX_CONFIG_TEMPLATE=/usr/local/etc/nginx.conf.erb \
PASSENGER_PID_FILE=/var/run/passenger.pid \
PASSENGER_PORT=8080 \
PASSENGER_PYTHON=/usr/bin/python3 \
/usr/local/bin/passenger "$@"

# remove tmp/always_restart.txt in development mode
if [ "$APPLICATION_ENV" == "dev" ]; then
    rm -f tmp/always_restart.txt && rmdir -p tmp
fi
