#!/bin/bash

case "$1" in
    start)

        rm -f /etc/supervisor/conf.d/supervisord.conf
        cp ./supervisord.conf /etc/supervisor/conf.d/

        rm -f /etc/nginx/sites-enabled/*
        cp ./php.conf /etc/nginx/sites-enabled/
        root=$(readlink -f "$2")
        if [ ! -d "$root" ]; then
            echo "No such directory: $2"
            exit 1
        fi
        sed -i "s#root /root;#root $root;#" /etc/nginx/sites-enabled/php.conf

        #sed -i "s#listen 80 default_server;#listen $port default_server;#" /etc/nginx/sites-enabled/php.conf

        APPLICATION_ENV=dev supervisord -c /etc/supervisor/conf.d/supervisord.conf

    ;;
esac
