on: 
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          tags: cs50/server:latest
          cache-from: type=registry,ref=cs50/server:buildcache
          cache-to: type=registry,ref=cs50/server:buildcache,mode=max

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/server:latest
