on:
    - push
    - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build for linux/amd64
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          platforms: linux/amd64
          tags: cs50/server:amd64
          cache-from: type=registry,ref=cs50/server:amd64-buildcache
          cache-to: type=registry,ref=cs50/server:amd64-buildcache,mode=max

      - name: Squash for linux/amd64
        run: |
          pip3 install docker-squash
          docker-squash --tag cs50/server:amd64 cs50/server:amd64

      - name: Push linux/amd64 build to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/server:amd64

      - name: Build for linux/arm64
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          platforms: linux/arm64
          tags: cs50/server:arm64
          cache-from: type=registry,ref=cs50/server:arm64-buildcache
          cache-to: type=registry,ref=cs50/server:arm64-buildcache,mode=max

      - name: Squash for linux/arm64
        run: |
          pip3 install docker-squash
          docker-squash --tag cs50/server:arm64 cs50/server:arm64

      - name: Push linux/arm64 build to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/server:arm64

      - name: Create multi-arch manifest and push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker manifest create cs50/server:latest \
          --amend cs50/server:amd64 \
          --amend cs50/server:arm64
          docker manifest push cs50/server:latest
